### ISSUE TITLE
rectangle domain with regular mesh?

### ISSUE THREAD

**Issue by lanzithinking** [liubenyuan/pyEIT#14]
Hi @liubenyuan ,

I see all your examples are defined on discs (2d) or balls (3d). Do you have functions that define the problem on rectangle domain with regular mesh? Thanks!

**Comment by liubenyuan** [comment]
Hi, thank you for your interest in pyeit.

You could see https://github.com/liubenyuan/pyEIT/blob/master/examples/mesh_distmesh2d.py
The example3 and example5 are rectangle based shapes, modify as you needed.

You need to add 16 or N electrodes (just the numbers/IDs of boundary nodes) in order to use the mesh in Forward and Inverse simulation.

**Comment by lanzithinking** [comment]
Thank you very much @liubenyuan !
